-- RLS DEEP FIX: Robust case-insensitive permissions for CMS
-- This script ensures admins can manage content regardless of email case or profile status.

-- 1. Ensure table exists with correct schema
CREATE TABLE IF NOT EXISTS public.cms_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  updated_by UUID DEFAULT auth.uid() REFERENCES auth.users(id)
);

-- 2. Enable RLS
ALTER TABLE public.cms_content ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing policies to prevent conflicts
DROP POLICY IF EXISTS "Allow public read access on cms_content" ON public.cms_content;
DROP POLICY IF EXISTS "Allow admin write access on cms_content" ON public.cms_content;
DROP POLICY IF EXISTS "Authenticated users can update" ON public.cms_content;

-- 4. Recreate policies with ILIKE (Case-Insensitive) and robust checks
-- SELECT is public
CREATE POLICY "Allow public read access on cms_content" 
ON public.cms_content FOR SELECT 
USING (true);

-- ALL (INSERT/UPDATE/DELETE) requires admin status
CREATE POLICY "Allow admin write access on cms_content" 
ON public.cms_content FOR ALL 
TO authenticated
USING (
  (LOWER(auth.jwt() ->> 'email') LIKE '%@admin.com')
  OR (LOWER(auth.jwt() ->> 'email') = 'admin@example.com')
  OR (EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE profiles.id = auth.uid() 
    AND profiles.is_admin = true
  ))
)
WITH CHECK (
  (LOWER(auth.jwt() ->> 'email') LIKE '%@admin.com')
  OR (LOWER(auth.jwt() ->> 'email') = 'admin@example.com')
  OR (EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE profiles.id = auth.uid() 
    AND profiles.is_admin = true
  ))
);

-- 5. Final verification: Grant all to authenticated role for this table specifically
-- (RLS still filters, but this ensures roles have table-level access)
GRANT ALL ON public.cms_content TO authenticated;
GRANT SELECT ON public.cms_content TO anon;
